name: "Gradle build & create release"
on:
  push:

permissions:
  contents: write

jobs:
  gradle-build-release:
    name: "Build Gradle project & create release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Capture Gradle build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build-artifacts
          path: "build/libs/*.jar"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/bat-velocity.jar
            README.md
            LICENSE
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
